source 'https://github.com/CocoaPods/Specs'

platform :ios, '11.0'
use_frameworks!

def base
	pod 'SwiftLint'	
	#pod 'SwiftFormat/CLI'
end

def firebase
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
end

target '{{cookiecutter.app_name}}' do
    base
    firebase
    
    target '{{cookiecutter.app_name}}Tests' do
    	#=NOTE: https://guides.cocoapods.org/syntax/podfile.html#inherit_bang
    	inherit! :search_paths 
	end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
