source 'https://github.com/CocoaPods/Specs'

platform :ios, '11.0'
use_frameworks!

def base_pods
	pod 'SwiftLint'	
	pod 'SwiftFormat/CLI'
end

def firebase
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
end

target '{{cookiecutter.app_name}}' do
    base_pods
    firebase_pods
    
    target '{{cookiecutter.app_name}}Tests' do
    	#=NOTE: https://guides.cocoapods.org/syntax/podfile.html#inherit_bang
    	inherit! :search_paths 
    	# pod 'OHHTTPStubs/Swift'
    	# pod 'Quick'
		# pod 'Nimble'
	end
end