name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Select
      run: sudo xcode-select -s '/Applications/Xcode_11.3.1.app/Contents/Developer'
    - name: Show version
      run: |
        xcodebuild -version
        pod --version
        carthage version
    - name: Carhtage Cache Clear
      run: |
        rm -rf ~/Library/Cache/carthage
        rm -rf ~/Library/Cache/org.carthage.CarthageKit
    - name: Install
      run: |
        brew install cookiecutter
        cookiecutter https://github.com/SatoshiN303/iOS-Blueprints-CleanArchitecture.git --no-input --config-file /Users/runner/work/iOS-Blueprints-CleanArchitecture/iOS-Blueprints-CleanArchitecture/default_config_for_actions.yml
    - name: Setup and Build
      run: |
        cd ./SampleApp
        ./bootstrap.sh
        xcodebuild build -workspace "SampleApp.xcworkspace" -scheme "SampleApp_Debug" -sdk iphonesimulator